module.exports.SUCCESS = 200;
module.exports.INTERNAL_SERVER_ERROR = 500;
module.exports.NOT_FOUND = 404;
module.exports.CREATED = 201;
module.exports.UNAUTHORIZED = 401;
module.exports.BAD_REQUEST = 400;
module.exports.ACTIVE = "Active";
module.exports.COMPLETED = "Completed";
module.exports.CANCELLED = "Cancelled";
module.exports.HIGH="high";
module.exports.LOW="low";
module.exports.ADMIN="admin"